---
apiVersion: v1
kind: Namespace
metadata:
  name: eks-cicd-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cicd-demo-dep
  namespace: eks-cicd-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-cicd-demo
  template:
    metadata:
      labels:
        app: eks-cicd-demo
    spec:
      containers:
      - name: eks-cicd-demo
        image: CONTAINER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-cicd-demo-svc
  namespace: eks-cicd-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: eks-cicd-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eks-cicd-demo-alb-ingress
  namespace: eks-cicd-staging
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: eks-cicd-demo-svc
              servicePort: 80
